enum TokenKind {
    BuiltInKeywordInt16 = 0,
    BuiltInKeywordInt32 = 1,
    BuiltInKeywordInt64 = 2,
    BuiltInKeywordString = 3,
    BuiltInKeywordChar = 4,
    BuiltInKeywordReturn = 5,
    BuiltInKeywordIf = 6,
    BuiltInKeywordElif = 7,
    BuiltInKeywordElse = 8,
    BuiltInKeywordNew = 9,
    BuiltInKeywordType = 10,
    ConstString,
    ConstChar,
    ConstInt32,
    ConstBool,
    ConstInt64,
    ConstInt16,
    ConstFloat,
    ConstFloat64,
    ConstFloat16,
    ConstIdentifier,
    SymbolCloseBracket,
    SymbolOpenBracket,
    ControlEndOfFile,
    SymbolOpenBrace,
    SymbolCloseBrace,
    SymbolEqual,
    OperatorEqualEqual,
    OperatorPlusEqual,
    SymbolPlus,
    OperatorMinusEqual,
    SymbolMinus,
    OperatorSlashEqual,
    SymbolSlash,
    SymbolStar,
    SymbolStarEqual,
    SymbolDot,
    SymbolColon,
    SymbolColonColon,
    SymbolMajor,
    OperatorMajorEqual,
    OperatorMinorEqual,
    SymbolMinor,
    SymbolOpenParenthesis,
    SymbolCloseParenthesis,
    ControlEndOfInstruction,
    SymbolComma,
    ControlEndOfLine,
    SymbolNegation,
    OperatorNotEqual,
}