enum TokenKind {
    BuiltInKeywordVar = 0,
    BuiltInKeywordFunc = 1,
    BuiltInKeywordTry = 2,
    BuiltInKeywordCatch = 3,
    BuiltInKeywordPublic = 4,
    BuiltInKeywordSelf = 5,
    BuiltInKeywordClass = 6,
    BuiltInKeywordField = 7,
    BuiltInKeywordDefine = 8,
    BuiltInKeywordExtern = 9,
    BuiltInKeywordUse = 10,
    BuiltInKeywordReturn = 11,
    BuiltInKeywordIf = 12,
    BuiltInKeywordElif = 13,
    BuiltInKeywordElse = 14,
    ConstString,
    ConstChar,
    ConstInt32,
    ConstBool,
    ConstInt64,
    ConstInt16,
    ConstFloat,
    ConstFloat64,
    ConstFloat16,
    ConstIdentifier,
    ConstNull,
    SymbolCloseBracket,
    SymbolOpenBracket,
    ControlEndOfFile,
    ControlIndent,
    SymbolOpenBrace,
    SymbolCloseBrace,
    SymbolEqual,
    OperatorEqualEqual,
    OperatorPlusEqual,
    SymbolPlus,
    OperatorMinusEqual,
    SymbolMinus,
    OperatorSlashEqual,
    SymbolSlash,
    SymbolStar,
    SymbolStarEqual,
    SymbolDot,
    SymbolColon,
    SymbolColonColon,
    SymbolMajor,
    OperatorMajorEqual,
    OperatorMinorEqual,
    SymbolMinor,
    SymbolOpenParenthesis,
    SymbolCloseParenthesis,
    ControlEndOfInstruction,
    SymbolComma,
    ControlEndOfLine,
    SymbolNegation,
    OperatorNotEqual,
}